# Generated by Django 3.2.4 on 2021-07-21 22:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210720_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-criado'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo'),
        ),
    ]
